### ISSUE TITLE
Implement Rclone Sync with S3 Storage

### ISSUE THREAD

**Issue by compgeniuses** [compgeniuses/ns8-paperless-ngx#31]
Ref: https://github.com/paperless-ngx/paperless-ngx/discussions/762

A proposal is made to Have Rclone within the pod that syncs the consume fodlers to an S3 Storage Location.

This could potentially enable other access methods for the document, equally potentiall Nextcloud.

```
version: "3.9"
services:
  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    volumes:
      - type: volume
        source: data
        target: /usr/src/paperless/data
        volume:
          nocopy: true
      - type: volume
        source: media
        target: /usr/src/paperless/media
        volume:
          nocopy: true
      - type: volume
        source: consume
        target: /usr/src/paperless/consume
        volume:
          nocopy: true   
      - export:/usr/src/paperless/export
...

volumes:
  media:    
    driver: rclone
    driver_opts:
      remote: 'homelab:homelab/paperless/media'
      allow_other: 'true'
      vfs_cache_mode: full
      poll_interval: 0
  consume:   
    driver: rclone
    driver_opts:
      remote: 'homelab:homelab/paperless/consume'
      allow_other: 'true'
      vfs_cache_mode: full
      poll_interval: 0 
...
You need to have rclone installed and a file for mapping your object storage like
[datas]
type = s3
provider = Minio (or Azure, S3, GCP)
env_auth = false
access_key_id = THE_ACCESS_KEY
secret_access_key = THE_SECRET_KEY
endpoint = THE_ENDPOINT
acl = bucket-owner-full-control
region = THE_REGION

See the documentation of rclone for more information
```
